package app 

import (
	"fmt"
	"https://github.com/dangolbeeker/Nerdeye/api/data.json"
	"net"
)

type Autogenerated struct {
	Us struct {
		Alabama struct {
			Auburn struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"auburn"`
			Bham struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bham"`
			Dothan struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"dothan"`
			Shoals struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"shoals"`
			Gadsden struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"gadsden"`
			Huntsville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"huntsville"`
			Mobile struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"mobile"`
			Montgomery struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"montgomery"`
			Tuscaloosa struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"tuscaloosa"`
		} `json:"Alabama"`
		Alaska struct {
			Anchorage struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"anchorage"`
			Fairbanks struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"fairbanks"`
			Kenai struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"kenai"`
			Juneau struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"juneau"`
		} `json:"Alaska"`
		Arizona struct {
			Flagstaff struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"flagstaff"`
			Mohave struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"mohave"`
			Phoenix struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"phoenix"`
			Prescott struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"prescott"`
			Showlow struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"showlow"`
			Sierravista struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sierravista"`
			Tucson struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"tucson"`
			Yuma struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"yuma"`
		} `json:"Arizona"`
		Arkansas struct {
			Fayar struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"fayar"`
			Fortsmith struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"fortsmith"`
			Jonesboro struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"jonesboro"`
			Littlerock struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"littlerock"`
			Texarkana struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"texarkana"`
		} `json:"Arkansas"`
		California struct {
			Bakersfield struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bakersfield"`
			Chico struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"chico"`
			Fresno struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"fresno"`
			Goldcountry struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"goldcountry"`
			Hanford struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"hanford"`
			Humboldt struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"humboldt"`
			Imperial struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"imperial"`
			Inlandempire struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"inlandempire"`
			Losangeles struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"losangeles"`
			Mendocino struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"mendocino"`
			Merced struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"merced"`
			Modesto struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"modesto"`
			Monterey struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"monterey"`
			Orangecounty struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"orangecounty"`
			Palmsprings struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"palmsprings"`
			Redding struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"redding"`
			Sacramento struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sacramento"`
			Sandiego struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sandiego"`
			Sfbay struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sfbay"`
			Slo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"slo"`
			Santabarbara struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"santabarbara"`
			Santamaria struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"santamaria"`
			Siskiyou struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"siskiyou"`
			Stockton struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"stockton"`
			Susanville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"susanville"`
			Ventura struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"ventura"`
			Visalia struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"visalia"`
			Yubasutter struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"yubasutter"`
		} `json:"California"`
		Colorado struct {
			Boulder struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"boulder"`
			Cosprings struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"cosprings"`
			Denver struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"denver"`
			Eastco struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"eastco"`
			Fortcollins struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"fortcollins"`
			Rockies struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"rockies"`
			Pueblo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"pueblo"`
			Westslope struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"westslope"`
		} `json:"Colorado"`
		Connecticut struct {
			Newlondon struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"newlondon"`
			Hartford struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"hartford"`
			Newhaven struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"newhaven"`
			Nwct struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"nwct"`
		} `json:"Connecticut"`
		Delaware struct {
			Delaware struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"delaware"`
		} `json:"Delaware"`
		DistrictOfColumbia struct {
			Washingtondc struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"washingtondc"`
		} `json:"District of Columbia"`
		Florida struct {
			Miami struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"miami"`
			Daytona struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"daytona"`
			Keys struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"keys"`
			Fortlauderdale struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"fortlauderdale"`
			Fortmyers struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"fortmyers"`
			Gainesville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"gainesville"`
			Cfl struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"cfl"`
			Jacksonville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"jacksonville"`
			Lakeland struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lakeland"`
			Lakecity struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lakecity"`
			Ocala struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"ocala"`
			Okaloosa struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"okaloosa"`
			Orlando struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"orlando"`
			Panamacity struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"panamacity"`
			Pensacola struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"pensacola"`
			Sarasota struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sarasota"`
			Spacecoast struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"spacecoast"`
			Staugustine struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"staugustine"`
			Tallahassee struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"tallahassee"`
			Tampa struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"tampa"`
			Treasure struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"treasure"`
		} `json:"Florida"`
		Georgia struct {
			Albanyga struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"albanyga"`
			Athensga struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"athensga"`
			Atlanta struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"atlanta"`
			Augusta struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"augusta"`
			Brunswick struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"brunswick"`
			Columbusga struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"columbusga"`
			Macon struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"macon"`
			Nwga struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"nwga"`
			Savannah struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"savannah"`
			Statesboro struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"statesboro"`
			Valdosta struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"valdosta"`
		} `json:"Georgia"`
		Hawaii struct {
			Honolulu struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"honolulu"`
		} `json:"Hawaii"`
		Idaho struct {
			Boise struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"boise"`
			Eastidaho struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"eastidaho"`
			Lewiston struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lewiston"`
			Twinfalls struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"twinfalls"`
		} `json:"Idaho"`
		Illinois struct {
			Bn struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bn"`
			Chambana struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"chambana"`
			Chicago struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"chicago"`
			Decatur struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"decatur"`
			Lasalle struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lasalle"`
			Mattoon struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"mattoon"`
			Peoria struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"peoria"`
			Rockford struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"rockford"`
			Carbondale struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"carbondale"`
			Springfieldil struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"springfieldil"`
			Quincy struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"quincy"`
		} `json:"Illinois"`
		Indiana struct {
			Bloomington struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bloomington"`
			Evansville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"evansville"`
			Fortwayne struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"fortwayne"`
			Indianapolis struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"indianapolis"`
			Kokomo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"kokomo"`
			Tippecanoe struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"tippecanoe"`
			Muncie struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"muncie"`
			Richmondin struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"richmondin"`
			Southbend struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"southbend"`
			Terrehaute struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"terrehaute"`
		} `json:"Indiana"`
		Iowa struct {
			Ames struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"ames"`
			Cedarrapids struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"cedarrapids"`
			Desmoines struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"desmoines"`
			Dubuque struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"dubuque"`
			Fortdodge struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"fortdodge"`
			Iowacity struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"iowacity"`
			Masoncity struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"masoncity"`
			Quadcities struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"quadcities"`
			Siouxcity struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"siouxcity"`
			Ottumwa struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"ottumwa"`
			Waterloo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"waterloo"`
		} `json:"Iowa"`
		Kansas struct {
			Lawrence struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lawrence"`
			Ksu struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"ksu"`
			Nwks struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"nwks"`
			Salina struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"salina"`
			Seks struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"seks"`
			Swks struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"swks"`
			Topeka struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"topeka"`
			Wichita struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"wichita"`
		} `json:"Kansas"`
		Kentucky struct {
			Bgky struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bgky"`
			Eastky struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"eastky"`
			Lexington struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lexington"`
			Louisville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"louisville"`
			Owensboro struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"owensboro"`
			Westky struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"westky"`
		} `json:"Kentucky"`
		Louisiana struct {
			Batonrouge struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"batonrouge"`
			Cenla struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"cenla"`
			Houma struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"houma"`
			Lafayette struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lafayette"`
			Lakecharles struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lakecharles"`
			Monroe struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"monroe"`
			Neworleans struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"neworleans"`
			Shreveport struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"shreveport"`
		} `json:"Louisiana"`
		Maine struct {
			Maine struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"maine"`
		} `json:"Maine"`
		Maryland struct {
			Annapolis struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"annapolis"`
			Baltimore struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"baltimore"`
			Easternshore struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"easternshore"`
			Frederick struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"frederick"`
			Smd struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"smd"`
			Westmd struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"westmd"`
		} `json:"Maryland"`
		Massachusetts struct {
			Boston struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"boston"`
			Capecod struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"capecod"`
			Southcoast struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"southcoast"`
			Westernmass struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"westernmass"`
			Worcester struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"worcester"`
		} `json:"Massachusetts"`
		Michigan struct {
			Annarbor struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"annarbor"`
			Battlecreek struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"battlecreek"`
			Centralmich struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"centralmich"`
			Detroit struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"detroit"`
			Flint struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"flint"`
			Grandrapids struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"grandrapids"`
			Holland struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"holland"`
			Jxn struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"jxn"`
			Kalamazoo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"kalamazoo"`
			Lansing struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lansing"`
			Monroemi struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"monroemi"`
			Muskegon struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"muskegon"`
			Nmi struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"nmi"`
			Porthuron struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"porthuron"`
			Saginaw struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"saginaw"`
			Swmi struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"swmi"`
			Thumb struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"thumb"`
			Up struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"up"`
		} `json:"Michigan"`
		Minnesota struct {
			Bemidji struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bemidji"`
			Brainerd struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"brainerd"`
			Duluth struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"duluth"`
			Mankato struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"mankato"`
			Minneapolis struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"minneapolis"`
			Rmn struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"rmn"`
			Marshall struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"marshall"`
			Stcloud struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"stcloud"`
		} `json:"Minnesota"`
		Mississippi struct {
			Gulfport struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"gulfport"`
			Hattiesburg struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"hattiesburg"`
			Jackson struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"jackson"`
			Meridian struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"meridian"`
			Northmiss struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"northmiss"`
			Natchez struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"natchez"`
		} `json:"Mississippi"`
		Missouri struct {
			Columbiamo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"columbiamo"`
			Joplin struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"joplin"`
			Kansascity struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"kansascity"`
			Kirksville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"kirksville"`
			Loz struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"loz"`
			Semo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"semo"`
			Springfield struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"springfield"`
			Stjoseph struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"stjoseph"`
			Stlouis struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"stlouis"`
		} `json:"Missouri"`
		Montana struct {
			Billings struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"billings"`
			Bozeman struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bozeman"`
			Butte struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"butte"`
			Greatfalls struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"greatfalls"`
			Helena struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"helena"`
			Kalispell struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"kalispell"`
			Missoula struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"missoula"`
			Montana struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"montana"`
		} `json:"Montana"`
		Nebraska struct {
			Grandisland struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"grandisland"`
			Lincoln struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lincoln"`
			Northplatte struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"northplatte"`
			Omaha struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"omaha"`
			Scottsbluff struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"scottsbluff"`
		} `json:"Nebraska"`
		Nevada struct {
			Elko struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"elko"`
			Lasvegas struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lasvegas"`
			Reno struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"reno"`
		} `json:"Nevada"`
		NewHampshire struct {
			Nh struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"nh"`
		} `json:"New Hampshire"`
		NewJersey struct {
			Cnj struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"cnj"`
			Jerseyshore struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"jerseyshore"`
			Newjersey struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"newjersey"`
			Southjersey struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"southjersey"`
		} `json:"New Jersey"`
		NewMexico struct {
			Albuquerque struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"albuquerque"`
			Clovis struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"clovis"`
			Farmington struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"farmington"`
			Lascruces struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lascruces"`
			Roswell struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"roswell"`
			Santafe struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"santafe"`
		} `json:"New Mexico"`
		NewYork struct {
			Albany struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"albany"`
			Binghamton struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"binghamton"`
			Buffalo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"buffalo"`
			Catskills struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"catskills"`
			Chautauqua struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"chautauqua"`
			Elmira struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"elmira"`
			Fingerlakes struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"fingerlakes"`
			Glensfalls struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"glensfalls"`
			Hudsonvalley struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"hudsonvalley"`
			Ithaca struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"ithaca"`
			Longisland struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"longisland"`
			Newyork struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"newyork"`
			Oneonta struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"oneonta"`
			Plattsburgh struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"plattsburgh"`
			Potsdam struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"potsdam"`
			Rochester struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"rochester"`
			Syracuse struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"syracuse"`
			Twintiers struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"twintiers"`
			Utica struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"utica"`
			Watertown struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"watertown"`
		} `json:"New York"`
		NorthCarolina struct {
			Asheville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"asheville"`
			Boone struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"boone"`
			Charlotte struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"charlotte"`
			Eastnc struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"eastnc"`
			Fayetteville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"fayetteville"`
			Greensboro struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"greensboro"`
			Hickory struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"hickory"`
			Onslow struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"onslow"`
			Outerbanks struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"outerbanks"`
			Raleigh struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"raleigh"`
			Wilmington struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"wilmington"`
			Winstonsalem struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"winstonsalem"`
		} `json:"North Carolina"`
		NorthDakota struct {
			Bismarck struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bismarck"`
			Fargo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"fargo"`
			Grandforks struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"grandforks"`
			Nd struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"nd"`
		} `json:"North Dakota"`
		Ohio struct {
			Akroncanton struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"akroncanton"`
			Ashtabula struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"ashtabula"`
			Athensohio struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"athensohio"`
			Chillicothe struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"chillicothe"`
			Cincinnati struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"cincinnati"`
			Cleveland struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"cleveland"`
			Columbus struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"columbus"`
			Dayton struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"dayton"`
			Limaohio struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"limaohio"`
			Mansfield struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"mansfield"`
			Sandusky struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sandusky"`
			Toledo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"toledo"`
			Tuscarawas struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"tuscarawas"`
			Youngstown struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"youngstown"`
			Zanesville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"zanesville"`
		} `json:"Ohio"`
		Oklahoma struct {
			Lawton struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lawton"`
			Enid struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"enid"`
			Oklahomacity struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"oklahomacity"`
			Stillwater struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"stillwater"`
			Tulsa struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"tulsa"`
		} `json:"Oklahoma"`
		Oregon struct {
			Bend struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bend"`
			Corvallis struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"corvallis"`
			Eastoregon struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"eastoregon"`
			Eugene struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"eugene"`
			Klamath struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"klamath"`
			Medford struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"medford"`
			Oregoncoast struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"oregoncoast"`
			Portland struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"portland"`
			Roseburg struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"roseburg"`
			Salem struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"salem"`
		} `json:"Oregon"`
		Pennsylvania struct {
			Altoona struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"altoona"`
			Chambersburg struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"chambersburg"`
			Erie struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"erie"`
			Harrisburg struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"harrisburg"`
			Lancaster struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lancaster"`
			Allentown struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"allentown"`
			Meadville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"meadville"`
			Philadelphia struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"philadelphia"`
			Pittsburgh struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"pittsburgh"`
			Poconos struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"poconos"`
			Reading struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"reading"`
			Scranton struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"scranton"`
			Pennstate struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"pennstate"`
			Williamsport struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"williamsport"`
			York struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"york"`
		} `json:"Pennsylvania"`
		RhodeIsland struct {
			Providence struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"providence"`
		} `json:"Rhode Island"`
		SouthCarolina struct {
			Charleston struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"charleston"`
			Columbia struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"columbia"`
			Florencesc struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"florencesc"`
			Greenville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"greenville"`
			Hiltonhead struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"hiltonhead"`
			Myrtlebeach struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"myrtlebeach"`
		} `json:"South Carolina"`
		SouthDakota struct {
			Nesd struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"nesd"`
			Csd struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"csd"`
			Rapidcity struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"rapidcity"`
			Siouxfalls struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"siouxfalls"`
			Sd struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sd"`
		} `json:"South Dakota"`
		Tennessee struct {
			Chattanooga struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"chattanooga"`
			Clarksville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"clarksville"`
			Cookeville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"cookeville"`
			Jacksontn struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"jacksontn"`
			Knoxville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"knoxville"`
			Memphis struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"memphis"`
			Nashville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"nashville"`
			Tricities struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"tricities"`
		} `json:"Tennessee"`
		Texas struct {
			Abilene struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"abilene"`
			Amarillo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"amarillo"`
			Austin struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"austin"`
			Beaumont struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"beaumont"`
			Brownsville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"brownsville"`
			Collegestation struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"collegestation"`
			Corpuschristi struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"corpuschristi"`
			Dallas struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"dallas"`
			Nacogdoches struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"nacogdoches"`
			Delrio struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"delrio"`
			Elpaso struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"elpaso"`
			Galveston struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"galveston"`
			Houston struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"houston"`
			Killeen struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"killeen"`
			Laredo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"laredo"`
			Lubbock struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lubbock"`
			Mcallen struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"mcallen"`
			Odessa struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"odessa"`
			Sanangelo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sanangelo"`
			Sanantonio struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sanantonio"`
			Sanmarcos struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sanmarcos"`
			Bigbend struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bigbend"`
			Texoma struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"texoma"`
			Easttexas struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"easttexas"`
			Victoriatx struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"victoriatx"`
			Waco struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"waco"`
			Wichitafalls struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"wichitafalls"`
		} `json:"Texas"`
		Utah struct {
			Logan struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"logan"`
			Ogden struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"ogden"`
			Provo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"provo"`
			Saltlakecity struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"saltlakecity"`
			Stgeorge struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"stgeorge"`
		} `json:"Utah"`
		Vermont struct {
			Vermont struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"vermont"`
		} `json:"Vermont"`
		Virginia struct {
			Charlottesville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"charlottesville"`
			Danville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"danville"`
			Fredericksburg struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"fredericksburg"`
			Norfolk struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"norfolk"`
			Harrisonburg struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"harrisonburg"`
			Lynchburg struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lynchburg"`
			Blacksburg struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"blacksburg"`
			Richmond struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"richmond"`
			Roanoke struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"roanoke"`
			Swva struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"swva"`
			Winchester struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"winchester"`
		} `json:"Virginia"`
		Washington struct {
			Bellingham struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bellingham"`
			Kpr struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"kpr"`
			Moseslake struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"moseslake"`
			Olympic struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"olympic"`
			Pullman struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"pullman"`
			Seattle struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"seattle"`
			Skagit struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"skagit"`
			Spokane struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"spokane"`
			Wenatchee struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"wenatchee"`
			Yakima struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"yakima"`
		} `json:"Washington"`
		WestVirginia struct {
			Charlestonwv struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"charlestonwv"`
			Martinsburg struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"martinsburg"`
			Huntington struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"huntington"`
			Morgantown struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"morgantown"`
			Wheeling struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"wheeling"`
			Parkersburg struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"parkersburg"`
			Swv struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"swv"`
			Wv struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"wv"`
		} `json:"West Virginia"`
		Wisconsin struct {
			Appleton struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"appleton"`
			Eauclaire struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"eauclaire"`
			Greenbay struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"greenbay"`
			Janesville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"janesville"`
			Racine struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"racine"`
			Lacrosse struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lacrosse"`
			Madison struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"madison"`
			Milwaukee struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"milwaukee"`
			Northernwi struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"northernwi"`
			Sheboygan struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sheboygan"`
			Wausau struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"wausau"`
		} `json:"Wisconsin"`
		Wyoming struct {
			Wyoming struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"wyoming"`
		} `json:"Wyoming"`
		Territories struct {
			Micronesia struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"micronesia"`
			Puertorico struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"puertorico"`
			Virgin struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"virgin"`
		} `json:"Territories"`
	} `json:"US"`
	Canada struct {
		Alberta struct {
			Calgary struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"calgary"`
			Edmonton struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"edmonton"`
			Ftmcmurray struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"ftmcmurray"`
			Lethbridge struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lethbridge"`
			Hat struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"hat"`
			Peace struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"peace"`
			Reddeer struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"reddeer"`
		} `json:"Alberta"`
		BritishColumbia struct {
			Cariboo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"cariboo"`
			Comoxvalley struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"comoxvalley"`
			Abbotsford struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"abbotsford"`
			Kamloops struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"kamloops"`
			Kelowna struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"kelowna"`
			Kootenays struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"kootenays"`
			Nanaimo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"nanaimo"`
			Princegeorge struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"princegeorge"`
			Skeena struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"skeena"`
			Sunshine struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sunshine"`
			Vancouver struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"vancouver"`
			Victoria struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"victoria"`
			Whistler struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"whistler"`
		} `json:"British Columbia"`
		Manitoba struct {
			Winnipeg struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"winnipeg"`
		} `json:"Manitoba"`
		NewBrunswick struct {
			Newbrunswick struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"newbrunswick"`
		} `json:"New Brunswick"`
		NewfoundlandAndLabrador struct {
			Newfoundland struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"newfoundland"`
		} `json:"Newfoundland and Labrador"`
		NorthwestTerritories struct {
			Territories struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"territories"`
			Yellowknife struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"yellowknife"`
		} `json:"Northwest Territories"`
		NovaScotia struct {
			Halifax struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"halifax"`
		} `json:"Nova Scotia"`
		Ontario struct {
			Barrie struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"barrie"`
			Belleville struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"belleville"`
			Brantford struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"brantford"`
			Chatham struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"chatham"`
			Cornwall struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"cornwall"`
			Guelph struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"guelph"`
			Hamilton struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"hamilton"`
			Kingston struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"kingston"`
			Kitchener struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"kitchener"`
			Londonon struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"londonon"`
			Niagara struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"niagara"`
			Ottawa struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"ottawa"`
			Owensound struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"owensound"`
			Peterborough struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"peterborough"`
			Sarnia struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sarnia"`
			Soo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"soo"`
			Sudbury struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sudbury"`
			Thunderbay struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"thunderbay"`
			Toronto struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"toronto"`
			Windsor struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"windsor"`
		} `json:"Ontario"`
		PrinceEdwardIsland struct {
			Pei struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"pei"`
		} `json:"Prince Edward Island"`
		Quebec struct {
			Montreal struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"montreal"`
			Quebec struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"quebec"`
			Saguenay struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"saguenay"`
			Sherbrooke struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sherbrooke"`
			Troisrivieres struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"troisrivieres"`
		} `json:"Quebec"`
		Saskatchewan struct {
			Regina struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"regina"`
			Saskatoon struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"saskatoon"`
		} `json:"Saskatchewan"`
		YukonTerritory struct {
			Whitehorse struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"whitehorse"`
		} `json:"Yukon Territory"`
	} `json:"Canada"`
	Europe struct {
		Austria struct {
			Vienna struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"vienna"`
		} `json:"Austria"`
		Belgium struct {
			Brussels struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"brussels"`
		} `json:"Belgium"`
		Bulgaria struct {
			Bulgaria struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bulgaria"`
		} `json:"Bulgaria"`
		Croatia struct {
			Zagreb struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"zagreb"`
		} `json:"Croatia"`
		CzechRepublic struct {
			Prague struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"prague"`
		} `json:"Czech Republic"`
		Denmark struct {
			Copenhagen struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"copenhagen"`
		} `json:"Denmark"`
		Finland struct {
			Helsinki struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"helsinki"`
		} `json:"Finland"`
		France struct {
			Bordeaux struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bordeaux"`
			Rennes struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"rennes"`
			Grenoble struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"grenoble"`
			Lille struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lille"`
			Loire struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"loire"`
			Lyon struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lyon"`
			Marseilles struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"marseilles"`
			Montpellier struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"montpellier"`
			Cotedazur struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"cotedazur"`
			Rouen struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"rouen"`
			Paris struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"paris"`
			Strasbourg struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"strasbourg"`
			Toulouse struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"toulouse"`
		} `json:"France"`
		Germany struct {
			Berlin struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"berlin"`
			Bremen struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bremen"`
			Cologne struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"cologne"`
			Dresden struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"dresden"`
			Dusseldorf struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"dusseldorf"`
			Essen struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"essen"`
			Frankfurt struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"frankfurt"`
			Hamburg struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"hamburg"`
			Hannover struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"hannover"`
			Heidelberg struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"heidelberg"`
			Kaiserslautern struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"kaiserslautern"`
			Leipzig struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"leipzig"`
			Munich struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"munich"`
			Nuremberg struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"nuremberg"`
			Stuttgart struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"stuttgart"`
		} `json:"Germany"`
		Greece struct {
			Athens struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"athens"`
		} `json:"Greece"`
		Hungary struct {
			Budapest struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"budapest"`
		} `json:"Hungary"`
		Iceland struct {
			Reykjavik struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"reykjavik"`
		} `json:"Iceland"`
		Ireland struct {
			Dublin struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"dublin"`
		} `json:"Ireland"`
		Italy struct {
			Bologna struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bologna"`
			Florence struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"florence"`
			Genoa struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"genoa"`
			Milan struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"milan"`
			Naples struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"naples"`
			Perugia struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"perugia"`
			Rome struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"rome"`
			Sardinia struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sardinia"`
			Sicily struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sicily"`
			Torino struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"torino"`
			Venice struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"venice"`
		} `json:"Italy"`
		Luxembourg struct {
			Luxembourg struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"luxembourg"`
		} `json:"Luxembourg"`
		Netherlands struct {
			Amsterdam struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"amsterdam"`
		} `json:"Netherlands"`
		Norway struct {
			Oslo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"oslo"`
		} `json:"Norway"`
		Poland struct {
			Warsaw struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"warsaw"`
		} `json:"Poland"`
		Portugal struct {
			Faro struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"faro"`
			Lisbon struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lisbon"`
			Porto struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"porto"`
		} `json:"Portugal"`
		Romania struct {
			Bucharest struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bucharest"`
		} `json:"Romania"`
		RussianFederation struct {
			Moscow struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"moscow"`
			Stpetersburg struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"stpetersburg"`
		} `json:"Russian Federation"`
		Spain struct {
			Alicante struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"alicante"`
			Baleares struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"baleares"`
			Barcelona struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"barcelona"`
			Bilbao struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bilbao"`
			Cadiz struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"cadiz"`
			Canarias struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"canarias"`
			Granada struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"granada"`
			Madrid struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"madrid"`
			Malaga struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"malaga"`
			Sevilla struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sevilla"`
			Valencia struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"valencia"`
		} `json:"Spain"`
		Sweden struct {
			Stockholm struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"stockholm"`
		} `json:"Sweden"`
		Switzerland struct {
			Basel struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"basel"`
			Bern struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bern"`
			Geneva struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"geneva"`
			Lausanne struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lausanne"`
			Zurich struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"zurich"`
		} `json:"Switzerland"`
		Turkey struct {
			Istanbul struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"istanbul"`
		} `json:"Turkey"`
		Ukraine struct {
			Ukraine struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"ukraine"`
		} `json:"Ukraine"`
		UnitedKingdom struct {
			Aberdeen struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"aberdeen"`
			Bath struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bath"`
			Belfast struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"belfast"`
			Birmingham struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"birmingham"`
			Brighton struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"brighton"`
			Bristol struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bristol"`
			Cambridge struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"cambridge"`
			Cardiff struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"cardiff"`
			Coventry struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"coventry"`
			Derby struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"derby"`
			Devon struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"devon"`
			Dundee struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"dundee"`
			Norwich struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"norwich"`
			Eastmids struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"eastmids"`
			Edinburgh struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"edinburgh"`
			Essex struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"essex"`
			Glasgow struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"glasgow"`
			Hampshire struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"hampshire"`
			Kent struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"kent"`
			Leeds struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"leeds"`
			Liverpool struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"liverpool"`
			London struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"london"`
			Manchester struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"manchester"`
			Newcastle struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"newcastle"`
			Nottingham struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"nottingham"`
			Oxford struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"oxford"`
			Sheffield struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sheffield"`
		} `json:"United Kingdom"`
	} `json:"Europe"`
	AsiaPacificAndMiddleEast struct {
		Bangladesh struct {
			Bangladesh struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bangladesh"`
		} `json:"Bangladesh"`
		China struct {
			Beijing struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"beijing"`
			Chengdu struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"chengdu"`
			Chongqing struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"chongqing"`
			Dalian struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"dalian"`
			Guangzhou struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"guangzhou"`
			Hangzhou struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"hangzhou"`
			Nanjing struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"nanjing"`
			Shanghai struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"shanghai"`
			Shenyang struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"shenyang"`
			Shenzhen struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"shenzhen"`
			Wuhan struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"wuhan"`
			Xian struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"xian"`
		} `json:"China"`
		GuamMicronesia struct {
			Micronesia struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"micronesia"`
		} `json:"Guam / Micronesia"`
		HongKong struct {
			Hongkong struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"hongkong"`
		} `json:"Hong Kong"`
		India struct {
			Ahmedabad struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"ahmedabad"`
			Bangalore struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bangalore"`
			Bhubaneswar struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bhubaneswar"`
			Chandigarh struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"chandigarh"`
			Chennai struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"chennai"`
			Delhi struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"delhi"`
			Goa struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"goa"`
			Hyderabad struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"hyderabad"`
			Indore struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"indore"`
			Jaipur struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"jaipur"`
			Kerala struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"kerala"`
			Kolkata struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"kolkata"`
			Lucknow struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lucknow"`
			Mumbai struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"mumbai"`
			Pune struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"pune"`
			Surat struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"surat"`
		} `json:"India"`
		Indonesia struct {
			Jakarta struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"jakarta"`
		} `json:"Indonesia"`
		Iran struct {
			Tehran struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"tehran"`
		} `json:"Iran"`
		Iraq struct {
			Baghdad struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"baghdad"`
		} `json:"Iraq"`
		IsraelAndPalestine struct {
			Haifa struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"haifa"`
			Jerusalem struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"jerusalem"`
			Telaviv struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"telaviv"`
			Ramallah struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"ramallah"`
		} `json:"Israel and Palestine"`
		Japan struct {
			Fukuoka struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"fukuoka"`
			Hiroshima struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"hiroshima"`
			Nagoya struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"nagoya"`
			Okinawa struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"okinawa"`
			Osaka struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"osaka"`
			Sapporo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sapporo"`
			Sendai struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sendai"`
			Tokyo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"tokyo"`
		} `json:"Japan"`
		Korea struct {
			Seoul struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"seoul"`
		} `json:"Korea"`
		Kuwait struct {
			Kuwait struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"kuwait"`
		} `json:"Kuwait"`
		Lebanon struct {
			Beirut struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"beirut"`
		} `json:"Lebanon"`
		Malaysia struct {
			Malaysia struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"malaysia"`
		} `json:"Malaysia"`
		Pakistan struct {
			Pakistan struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"pakistan"`
		} `json:"Pakistan"`
		Philippines struct {
			Bacolod struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bacolod"`
			Naga struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"naga"`
			Cdo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"cdo"`
			Cebu struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"cebu"`
			Davaocity struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"davaocity"`
			Iloilo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"iloilo"`
			Manila struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"manila"`
			Pampanga struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"pampanga"`
			Zamboanga struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"zamboanga"`
		} `json:"Philippines"`
		Singapore struct {
			Singapore struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"singapore"`
		} `json:"Singapore"`
		Taiwan struct {
			Taipei struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"taipei"`
		} `json:"Taiwan"`
		Thailand struct {
			Bangkok struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bangkok"`
		} `json:"Thailand"`
		UnitedArabEmirates struct {
			Dubai struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"dubai"`
		} `json:"United Arab Emirates"`
		Vietnam struct {
			Vietnam struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"vietnam"`
		} `json:"Vietnam"`
	} `json:"Asia, Pacific and Middle East"`
	Oceania struct {
		Australia struct {
			Adelaide struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"adelaide"`
			Brisbane struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"brisbane"`
			Cairns struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"cairns"`
			Canberra struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"canberra"`
			Darwin struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"darwin"`
			Goldcoast struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"goldcoast"`
			Melbourne struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"melbourne"`
			Ntl struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"ntl"`
			Perth struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"perth"`
			Sydney struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"sydney"`
			Hobart struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"hobart"`
			Wollongong struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"wollongong"`
		} `json:"Australia"`
		NewZealand struct {
			Auckland struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"auckland"`
			Christchurch struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"christchurch"`
			Dunedin struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"dunedin"`
			Wellington struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"wellington"`
		} `json:"New Zealand"`
	} `json:"Oceania"`
	LatinAmericaAndCaribbean struct {
		Argentina struct {
			Buenosaires struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"buenosaires"`
		} `json:"Argentina"`
		Bolivia struct {
			Lapaz struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lapaz"`
		} `json:"Bolivia"`
		Brazil struct {
			Belohorizonte struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"belohorizonte"`
			Brasilia struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"brasilia"`
			Curitiba struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"curitiba"`
			Fortaleza struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"fortaleza"`
			Portoalegre struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"portoalegre"`
			Recife struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"recife"`
			Rio struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"rio"`
			Salvador struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"salvador"`
			Saopaulo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"saopaulo"`
		} `json:"Brazil"`
		CaribbeanIslands struct {
			Caribbean struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"caribbean"`
		} `json:"Caribbean Islands"`
		Chile struct {
			Santiago struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"santiago"`
		} `json:"Chile"`
		Colombia struct {
			Colombia struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"colombia"`
		} `json:"Colombia"`
		CostaRica struct {
			Costarica struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"costarica"`
		} `json:"Costa Rica"`
		DominicanRepublic struct {
			Santodomingo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"santodomingo"`
		} `json:"Dominican Republic"`
		Ecuador struct {
			Quito struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"quito"`
		} `json:"Ecuador"`
		ElSalvador struct {
			Elsalvador struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"elsalvador"`
		} `json:"El Salvador"`
		Guatemala struct {
			Guatemala struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"guatemala"`
		} `json:"Guatemala"`
		Mexico struct {
			Acapulco struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"acapulco"`
			Bajasur struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"bajasur"`
			Chihuahua struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"chihuahua"`
			Juarez struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"juarez"`
			Guadalajara struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"guadalajara"`
			Guanajuato struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"guanajuato"`
			Hermosillo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"hermosillo"`
			Mazatlan struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"mazatlan"`
			Mexicocity struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"mexicocity"`
			Monterrey struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"monterrey"`
			Oaxaca struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"oaxaca"`
			Puebla struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"puebla"`
			Pv struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"pv"`
			Tijuana struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"tijuana"`
			Veracruz struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"veracruz"`
			Yucatan struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"yucatan"`
		} `json:"Mexico"`
		Nicaragua struct {
			Managua struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"managua"`
		} `json:"Nicaragua"`
		Panama struct {
			Panama struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"panama"`
		} `json:"Panama"`
		Peru struct {
			Lima struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"lima"`
		} `json:"Peru"`
		PuertoRico struct {
			Puertorico struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"puertorico"`
		} `json:"Puerto Rico"`
		Uruguay struct {
			Montevideo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"montevideo"`
		} `json:"Uruguay"`
		Venezuela struct {
			Caracas struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"caracas"`
		} `json:"Venezuela"`
		VirginIslandsUS struct {
			Virgin struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"virgin"`
		} `json:"Virgin Islands, U.S."`
	} `json:"Latin America and Caribbean"`
	Africa struct {
		Egypt struct {
			Cairo struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"cairo"`
		} `json:"Egypt"`
		Ethiopia struct {
			Addisababa struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"addisababa"`
		} `json:"Ethiopia"`
		Ghana struct {
			Accra struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"accra"`
		} `json:"Ghana"`
		Kenya struct {
			Kenya struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"kenya"`
		} `json:"Kenya"`
		Morocco struct {
			Casablanca struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"casablanca"`
		} `json:"Morocco"`
		SouthAfrica struct {
			Capetown struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"capetown"`
			Durban struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"durban"`
			Johannesburg struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"johannesburg"`
			Pretoria struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"pretoria"`
		} `json:"South Africa"`
		Tunisia struct {
			Tunis struct {
				Name string `json:"name"`
				Link string `json:"link"`
			} `json:"tunis"`
		} `json:"Tunisia"`
	} `json:"Africa"`
}